/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tomato/scene.gltf 
Author: B.F.C (https://sketchfab.com/B.F.C)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tomato-e1b22565fc6942a2866bdf8b51cf567a
Title: 'tomato'
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tomato/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.024, 4.881, -0.044]} rotation={[1.59, 0, 0]}>
          <mesh geometry={nodes.Plane_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane_0_1.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane_0_2.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane_0_3.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane_0_4.geometry} material={materials.Material} />
          <mesh geometry={nodes.Plane_0_5.geometry} material={materials.Material} />
        </group>
        <group position={[-0.014, 0.049, 0.879]} scale={0.388}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_3.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_4.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_5.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_6.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_7.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_8.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_9.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_10.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_11.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_0_12.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tomato/scene.gltf')
