/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/pickles2/scene.gltf --output src/components/Model.jsx 
Author: Etman (https://sketchfab.com/Etman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pickles-4b8c7e8412fb409285528e79b70d1891
Title: pickles
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pickles2/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} position={[0, 0, -1498.969]} rotation={[-Math.PI / 2, 0, 0]} scale={197.772} />
      <mesh geometry={nodes.metal_metal_0.geometry} material={materials.metal} position={[0, 0, -1498.969]} rotation={[-Math.PI / 2, 0, 0]} scale={197.772} />
      <mesh geometry={nodes.cucumber_cucumber_0.geometry} material={materials.cucumber} position={[140.605, 418.819, -1440.278]} rotation={[1.583, -0.109, 2.687]} scale={48.228} />
      <mesh geometry={nodes.water_water_0.geometry} material={materials.water} position={[0, 0, -1498.969]} rotation={[-Math.PI / 2, 0, 0]} scale={197.772} />
      <mesh geometry={nodes.cucumber001_cucumber_0.geometry} material={materials.cucumber} position={[-140.547, 121.712, -1450.968]} rotation={[-1.644, -0.044, -0.259]} scale={[48.228, 48.228, 39.769]} />
      <mesh geometry={nodes.cucumber002_cucumber_0.geometry} material={materials.cucumber} position={[23.789, 129.135, -1619.149]} rotation={[-1.696, 0.003, -0.251]} scale={[48.228, 48.228, 45.05]} />
      <mesh geometry={nodes.cucumber003_cucumber_0.geometry} material={materials.cucumber} position={[16.929, 126.799, -1500.835]} rotation={[-1.662, -0.285, 0.168]} scale={48.228} />
      <mesh geometry={nodes.cucumber004_cucumber_0.geometry} material={materials.cucumber} position={[0.911, 122.648, -1368.342]} rotation={[-1.435, 0.028, 0.016]} scale={42.357} />
      <mesh geometry={nodes.cucumber005_cucumber_0.geometry} material={materials.cucumber} position={[-146.763, 372.337, -1574.761]} rotation={[1.548, 0.225, -3.116]} scale={43.455} />
      <mesh geometry={nodes.cucumber006_cucumber_0.geometry} material={materials.cucumber} position={[109.502, 113.655, -1557.204]} rotation={[-1.646, 0.135, 0.244]} scale={[40.399, 51.996, 36.986]} />
      <mesh geometry={nodes.cucumber007_cucumber_0.geometry} material={materials.cucumber} position={[80.946, 417.989, -1362.139]} rotation={[-1.6, -0.297, -0.445]} scale={[41.058, 49.65, 37.212]} />
      <mesh geometry={nodes.cucumber008_cucumber_0.geometry} material={materials.cucumber} position={[-158.405, 478.549, -1519.726]} rotation={[-1.559, 0.025, -1.067]} scale={[44.673, 44.673, 38.828]} />
      <mesh geometry={nodes.cucumber009_cucumber_0.geometry} material={materials.cucumber} position={[103.311, 449.475, -1623.185]} rotation={[-1.593, -0.412, -0.556]} scale={[51.427, 51.427, 40.33]} />
      <mesh geometry={nodes.cucumber010_cucumber_0.geometry} material={materials.cucumber} position={[-55.008, 656.064, -1476.69]} rotation={[1.702, 0.404, 2.613]} scale={48.228} />
      <mesh geometry={nodes.cucumber011_cucumber_0.geometry} material={materials.cucumber} position={[-83.838, 345.286, -1378.891]} rotation={[-1.564, -0.028, 1.986]} scale={[49.163, 51.504, 48.228]} />
      <mesh geometry={nodes.cucumber012_cucumber_0.geometry} material={materials.cucumber} position={[-116.178, 565.825, -1596.558]} rotation={[1.754, 0.203, -0.216]} scale={[39.13, 47.82, 35.203]} />
      <mesh geometry={nodes.cucumber013_cucumber_0.geometry} material={materials.cucumber} position={[89.093, 684.333, -1436.231]} rotation={[1.968, 0.239, 2.487]} scale={[48.222, 48.226, 40.241]} />
    </group>
  )
}

useGLTF.preload('/pickles2/scene.gltf')
